### PR TITLE
Working Vite setup removed spritezero

### PR DESCRIPTION
**Pull request by mathiash98**
Everything seems to be working fine with Node20 and Mac M1

Main changes:
- Migrated from webpack to Vite for building and serving
- Removed usage of sprites
- Converted all SVGs to PNG manually using `rsvg-convert` -> I did not find any good svg to png convertes that was usable in this Vite setup 🤔 
- Converted many JS files to TS

Relates to #165

### CODE REVIEW

**Comment by russss** [comment]
Thanks for doing this, and sorry for the slow reply! There are a few issues I'd like to fix before merging this - I might do these myself but I'm leaving them here mostly so I remember them if I get distracted...

* Currently this doesn't load the retina images - we need to detect retina support on the client and dynamically load the correct image (passing `pixelRatio: 2` in the [StyleImageMetadata](https://maplibre.org/maplibre-gl-js/docs/API/types/maplibregl.StyleImageMetadata/) to `map.addImage`. We probably shouldn't import the images in this case, and instead load them using `fetch()`.
* I'd really like to try and dynamically render these images to png - this will require a vite plugin but it doesn't look too difficult. [resvg-js](https://github.com/yisibl/resvg-js) looks promising for this.

**Comment by russss** [comment]
Merged in 352c9aca1c870023a72f2d836a1b343684925247. I wrote [a vite plugin](https://www.npmjs.com/package/vite-plugin-render-svg) to do the PNG rendering

**Comment by mathiash98** [comment]
> Merged in [352c9ac](https://github.com/openinframap/openinframap/commit/352c9aca1c870023a72f2d836a1b343684925247). I wrote [a vite plugin](https://www.npmjs.com/package/vite-plugin-render-svg) to do the PNG rendering

Great! Now we can more easily implement other feature requests 🚀

**Comment by russss** [comment]
I have a bit of refactoring/cleanup coming up too, so maybe best to hold off making too many changes until that's finished

**Comment by flacombe** [comment]
It would be good to take care of #163 and #93 as well.
I'm not sure #93 should be closed immediately as master may already fully cover its changes.

**Pull request closed without merging**
