### PR TITLE
Add dockerfile for Tegola with config generation

### PR DESCRIPTION
**Pull request by flacombe**
This PR introduces a dockerfile for tegola to ease build process.
It connects to remote postgis and expired imposm3 directory to wipe expired tiles from cache

The docker build operation includes the config.toml file generation with Python help.

### CODE REVIEW

**Comment by flacombe** [comment]
@russss would you like to consider again merging this PR at least please?

It shouldn't alter the current running, only providing docker capability for ones who use it.
The only change I notice is to define an env variable `DB_URI` to allow to Tegola to connect (used in tegola.yml)

**Comment by russss** [comment]
Ah, well, the problem is that I've also Dockerised Tegola now but I've done it a different way (see [tegola/Dockerfile](https://github.com/openinframap/openinframap/blob/369af66b7c57f8d7177b71aba4835240e723339c/tegola/Dockerfile) and [tegola/Dockerfile.expiry](https://github.com/openinframap/openinframap/blob/369af66b7c57f8d7177b71aba4835240e723339c/tegola/Dockerfile.expiry)). Sorry about that, I really should have mentioned in this PR!

I run these containers on top of Kubernetes so the scheduling aspect of the seeding is handled by kubernetes and spawns a new instance of the same Tegola container image (this part is in my kubernetes config which is not public). However even if I wasn't using Kubernetes I'd probably still just use `docker run` in the host machine crontab in preference to putting cron into the dockerfile (which does complicate things as you've seen).

**Comment by flacombe** [comment]
Oh that's fine. I didn't noticed those new Dockerfiles.

So I close this PR.
Can I propose a slight change to allow selecting the config used at docker build?
It will keep the default to local tegola.yml and layers.yml

**Comment by russss** [comment]
Yes, happy to accept a PR for that if it preserves the current behaviour by default.

**Comment by flacombe** [comment]
Wait for it

**Pull request closed without merging**
